particle minecraft:basic_flame_particle ~-24 ~0.5 ~0
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-23 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-23 ~0.5 ~0
particle minecraft:basic_flame_particle ~-23 ~0.5 ~1
particle minecraft:basic_flame_particle ~-23 ~0.5 ~2
particle minecraft:basic_flame_particle ~-23 ~0.5 ~3
particle minecraft:basic_flame_particle ~-23 ~0.5 ~4
particle minecraft:basic_flame_particle ~-23 ~0.5 ~5
particle minecraft:basic_flame_particle ~-23 ~0.5 ~6
particle minecraft:basic_flame_particle ~-22 ~0.5 ~-9
particle minecraft:basic_flame_particle ~-22 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-22 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-22 ~0.5 ~7
particle minecraft:basic_flame_particle ~-22 ~0.5 ~8
particle minecraft:basic_flame_particle ~-22 ~0.5 ~9
particle minecraft:basic_flame_particle ~-21 ~0.5 ~-11
particle minecraft:basic_flame_particle ~-21 ~0.5 ~-10
particle minecraft:basic_flame_particle ~-21 ~0.5 ~10
particle minecraft:basic_flame_particle ~-21 ~0.5 ~11
particle minecraft:basic_flame_particle ~-20 ~0.5 ~-12
particle minecraft:basic_flame_particle ~-20 ~0.5 ~12
particle minecraft:basic_flame_particle ~-19 ~0.5 ~-14
particle minecraft:basic_flame_particle ~-19 ~0.5 ~14
particle minecraft:basic_flame_particle ~-18 ~0.5 ~-15
particle minecraft:basic_flame_particle ~-18 ~0.5 ~15
particle minecraft:basic_flame_particle ~-17 ~0.5 ~-16
particle minecraft:basic_flame_particle ~-17 ~0.5 ~16
particle minecraft:basic_flame_particle ~-16 ~0.5 ~-17
particle minecraft:basic_flame_particle ~-16 ~0.5 ~17
particle minecraft:basic_flame_particle ~-15 ~0.5 ~-18
particle minecraft:basic_flame_particle ~-15 ~0.5 ~18
particle minecraft:basic_flame_particle ~-14 ~0.5 ~-19
particle minecraft:basic_flame_particle ~-14 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-14 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-14 ~0.5 ~0
particle minecraft:basic_flame_particle ~-14 ~0.5 ~1
particle minecraft:basic_flame_particle ~-14 ~0.5 ~2
particle minecraft:basic_flame_particle ~-14 ~0.5 ~3
particle minecraft:basic_flame_particle ~-14 ~0.5 ~19
particle minecraft:basic_flame_particle ~-13 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-13 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-13 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-13 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-13 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-13 ~0.5 ~0
particle minecraft:basic_flame_particle ~-13 ~0.5 ~1
particle minecraft:basic_flame_particle ~-13 ~0.5 ~2
particle minecraft:basic_flame_particle ~-13 ~0.5 ~3
particle minecraft:basic_flame_particle ~-13 ~0.5 ~4
particle minecraft:basic_flame_particle ~-13 ~0.5 ~5
particle minecraft:basic_flame_particle ~-13 ~0.5 ~6
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-20
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-12 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-12 ~0.5 ~0
particle minecraft:basic_flame_particle ~-12 ~0.5 ~1
particle minecraft:basic_flame_particle ~-12 ~0.5 ~2
particle minecraft:basic_flame_particle ~-12 ~0.5 ~3
particle minecraft:basic_flame_particle ~-12 ~0.5 ~4
particle minecraft:basic_flame_particle ~-12 ~0.5 ~5
particle minecraft:basic_flame_particle ~-12 ~0.5 ~6
particle minecraft:basic_flame_particle ~-12 ~0.5 ~7
particle minecraft:basic_flame_particle ~-12 ~0.5 ~8
particle minecraft:basic_flame_particle ~-12 ~0.5 ~20
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-21
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-11 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-11 ~0.5 ~0
particle minecraft:basic_flame_particle ~-11 ~0.5 ~1
particle minecraft:basic_flame_particle ~-11 ~0.5 ~2
particle minecraft:basic_flame_particle ~-11 ~0.5 ~3
particle minecraft:basic_flame_particle ~-11 ~0.5 ~4
particle minecraft:basic_flame_particle ~-11 ~0.5 ~5
particle minecraft:basic_flame_particle ~-11 ~0.5 ~6
particle minecraft:basic_flame_particle ~-11 ~0.5 ~7
particle minecraft:basic_flame_particle ~-11 ~0.5 ~8
particle minecraft:basic_flame_particle ~-11 ~0.5 ~9
particle minecraft:basic_flame_particle ~-11 ~0.5 ~21
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-21
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-9
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-10 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-10 ~0.5 ~0
particle minecraft:basic_flame_particle ~-10 ~0.5 ~1
particle minecraft:basic_flame_particle ~-10 ~0.5 ~2
particle minecraft:basic_flame_particle ~-10 ~0.5 ~3
particle minecraft:basic_flame_particle ~-10 ~0.5 ~4
particle minecraft:basic_flame_particle ~-10 ~0.5 ~5
particle minecraft:basic_flame_particle ~-10 ~0.5 ~6
particle minecraft:basic_flame_particle ~-10 ~0.5 ~7
particle minecraft:basic_flame_particle ~-10 ~0.5 ~8
particle minecraft:basic_flame_particle ~-10 ~0.5 ~9
particle minecraft:basic_flame_particle ~-10 ~0.5 ~10
particle minecraft:basic_flame_particle ~-10 ~0.5 ~21
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-22
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-10
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-9
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-9 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-9 ~0.5 ~0
particle minecraft:basic_flame_particle ~-9 ~0.5 ~1
particle minecraft:basic_flame_particle ~-9 ~0.5 ~2
particle minecraft:basic_flame_particle ~-9 ~0.5 ~3
particle minecraft:basic_flame_particle ~-9 ~0.5 ~4
particle minecraft:basic_flame_particle ~-9 ~0.5 ~5
particle minecraft:basic_flame_particle ~-9 ~0.5 ~6
particle minecraft:basic_flame_particle ~-9 ~0.5 ~7
particle minecraft:basic_flame_particle ~-9 ~0.5 ~8
particle minecraft:basic_flame_particle ~-9 ~0.5 ~9
particle minecraft:basic_flame_particle ~-9 ~0.5 ~10
particle minecraft:basic_flame_particle ~-9 ~0.5 ~11
particle minecraft:basic_flame_particle ~-9 ~0.5 ~22
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-22
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-11
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-10
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-9
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-8 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-8 ~0.5 ~0
particle minecraft:basic_flame_particle ~-8 ~0.5 ~1
particle minecraft:basic_flame_particle ~-8 ~0.5 ~2
particle minecraft:basic_flame_particle ~-8 ~0.5 ~3
particle minecraft:basic_flame_particle ~-8 ~0.5 ~4
particle minecraft:basic_flame_particle ~-8 ~0.5 ~5
particle minecraft:basic_flame_particle ~-8 ~0.5 ~6
particle minecraft:basic_flame_particle ~-8 ~0.5 ~7
particle minecraft:basic_flame_particle ~-8 ~0.5 ~8
particle minecraft:basic_flame_particle ~-8 ~0.5 ~9
particle minecraft:basic_flame_particle ~-8 ~0.5 ~10
particle minecraft:basic_flame_particle ~-8 ~0.5 ~11
particle minecraft:basic_flame_particle ~-8 ~0.5 ~12
particle minecraft:basic_flame_particle ~-8 ~0.5 ~22
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-22
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-12
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-11
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-10
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-9
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-4
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-7 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-7 ~0.5 ~0
particle minecraft:basic_flame_particle ~-7 ~0.5 ~1
particle minecraft:basic_flame_particle ~-7 ~0.5 ~2
particle minecraft:basic_flame_particle ~-7 ~0.5 ~3
particle minecraft:basic_flame_particle ~-7 ~0.5 ~4
particle minecraft:basic_flame_particle ~-7 ~0.5 ~5
particle minecraft:basic_flame_particle ~-7 ~0.5 ~6
particle minecraft:basic_flame_particle ~-7 ~0.5 ~7
particle minecraft:basic_flame_particle ~-7 ~0.5 ~8
particle minecraft:basic_flame_particle ~-7 ~0.5 ~9
particle minecraft:basic_flame_particle ~-7 ~0.5 ~10
particle minecraft:basic_flame_particle ~-7 ~0.5 ~11
particle minecraft:basic_flame_particle ~-7 ~0.5 ~12
particle minecraft:basic_flame_particle ~-7 ~0.5 ~22
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-12
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-11
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-10
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-3
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-6 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-6 ~0.5 ~0
particle minecraft:basic_flame_particle ~-6 ~0.5 ~1
particle minecraft:basic_flame_particle ~-6 ~0.5 ~2
particle minecraft:basic_flame_particle ~-6 ~0.5 ~3
particle minecraft:basic_flame_particle ~-6 ~0.5 ~4
particle minecraft:basic_flame_particle ~-6 ~0.5 ~5
particle minecraft:basic_flame_particle ~-6 ~0.5 ~6
particle minecraft:basic_flame_particle ~-6 ~0.5 ~7
particle minecraft:basic_flame_particle ~-6 ~0.5 ~8
particle minecraft:basic_flame_particle ~-6 ~0.5 ~9
particle minecraft:basic_flame_particle ~-6 ~0.5 ~10
particle minecraft:basic_flame_particle ~-6 ~0.5 ~11
particle minecraft:basic_flame_particle ~-6 ~0.5 ~12
particle minecraft:basic_flame_particle ~-6 ~0.5 ~13
particle minecraft:basic_flame_particle ~-6 ~0.5 ~23
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-13
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-12
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-11
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-2
particle minecraft:basic_flame_particle ~-5 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-5 ~0.5 ~0
particle minecraft:basic_flame_particle ~-5 ~0.5 ~1
particle minecraft:basic_flame_particle ~-5 ~0.5 ~2
particle minecraft:basic_flame_particle ~-5 ~0.5 ~3
particle minecraft:basic_flame_particle ~-5 ~0.5 ~4
particle minecraft:basic_flame_particle ~-5 ~0.5 ~5
particle minecraft:basic_flame_particle ~-5 ~0.5 ~6
particle minecraft:basic_flame_particle ~-5 ~0.5 ~7
particle minecraft:basic_flame_particle ~-5 ~0.5 ~8
particle minecraft:basic_flame_particle ~-5 ~0.5 ~9
particle minecraft:basic_flame_particle ~-5 ~0.5 ~10
particle minecraft:basic_flame_particle ~-5 ~0.5 ~11
particle minecraft:basic_flame_particle ~-5 ~0.5 ~12
particle minecraft:basic_flame_particle ~-5 ~0.5 ~13
particle minecraft:basic_flame_particle ~-5 ~0.5 ~23
particle minecraft:basic_flame_particle ~-4 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-4 ~0.5 ~-13
particle minecraft:basic_flame_particle ~-4 ~0.5 ~-12
particle minecraft:basic_flame_particle ~-4 ~0.5 ~-1
particle minecraft:basic_flame_particle ~-4 ~0.5 ~0
particle minecraft:basic_flame_particle ~-4 ~0.5 ~1
particle minecraft:basic_flame_particle ~-4 ~0.5 ~2
particle minecraft:basic_flame_particle ~-4 ~0.5 ~3
particle minecraft:basic_flame_particle ~-4 ~0.5 ~4
particle minecraft:basic_flame_particle ~-4 ~0.5 ~5
particle minecraft:basic_flame_particle ~-4 ~0.5 ~6
particle minecraft:basic_flame_particle ~-4 ~0.5 ~7
particle minecraft:basic_flame_particle ~-4 ~0.5 ~8
particle minecraft:basic_flame_particle ~-4 ~0.5 ~9
particle minecraft:basic_flame_particle ~-4 ~0.5 ~10
particle minecraft:basic_flame_particle ~-4 ~0.5 ~11
particle minecraft:basic_flame_particle ~-4 ~0.5 ~12
particle minecraft:basic_flame_particle ~-4 ~0.5 ~13
particle minecraft:basic_flame_particle ~-4 ~0.5 ~23
particle minecraft:basic_flame_particle ~-3 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-3 ~0.5 ~-13
particle minecraft:basic_flame_particle ~-3 ~0.5 ~0
particle minecraft:basic_flame_particle ~-3 ~0.5 ~1
particle minecraft:basic_flame_particle ~-3 ~0.5 ~2
particle minecraft:basic_flame_particle ~-3 ~0.5 ~3
particle minecraft:basic_flame_particle ~-3 ~0.5 ~4
particle minecraft:basic_flame_particle ~-3 ~0.5 ~5
particle minecraft:basic_flame_particle ~-3 ~0.5 ~6
particle minecraft:basic_flame_particle ~-3 ~0.5 ~7
particle minecraft:basic_flame_particle ~-3 ~0.5 ~8
particle minecraft:basic_flame_particle ~-3 ~0.5 ~9
particle minecraft:basic_flame_particle ~-3 ~0.5 ~10
particle minecraft:basic_flame_particle ~-3 ~0.5 ~11
particle minecraft:basic_flame_particle ~-3 ~0.5 ~12
particle minecraft:basic_flame_particle ~-3 ~0.5 ~13
particle minecraft:basic_flame_particle ~-3 ~0.5 ~14
particle minecraft:basic_flame_particle ~-3 ~0.5 ~23
particle minecraft:basic_flame_particle ~-2 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-2 ~0.5 ~-13
particle minecraft:basic_flame_particle ~-2 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-2 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-2 ~0.5 ~0
particle minecraft:basic_flame_particle ~-2 ~0.5 ~1
particle minecraft:basic_flame_particle ~-2 ~0.5 ~2
particle minecraft:basic_flame_particle ~-2 ~0.5 ~3
particle minecraft:basic_flame_particle ~-2 ~0.5 ~4
particle minecraft:basic_flame_particle ~-2 ~0.5 ~5
particle minecraft:basic_flame_particle ~-2 ~0.5 ~6
particle minecraft:basic_flame_particle ~-2 ~0.5 ~7
particle minecraft:basic_flame_particle ~-2 ~0.5 ~8
particle minecraft:basic_flame_particle ~-2 ~0.5 ~9
particle minecraft:basic_flame_particle ~-2 ~0.5 ~10
particle minecraft:basic_flame_particle ~-2 ~0.5 ~11
particle minecraft:basic_flame_particle ~-2 ~0.5 ~12
particle minecraft:basic_flame_particle ~-2 ~0.5 ~13
particle minecraft:basic_flame_particle ~-2 ~0.5 ~14
particle minecraft:basic_flame_particle ~-2 ~0.5 ~23
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-23
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-13
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-8
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-7
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-6
particle minecraft:basic_flame_particle ~-1 ~0.5 ~-5
particle minecraft:basic_flame_particle ~-1 ~0.5 ~0
particle minecraft:basic_flame_particle ~-1 ~0.5 ~1
particle minecraft:basic_flame_particle ~-1 ~0.5 ~2
particle minecraft:basic_flame_particle ~-1 ~0.5 ~3
particle minecraft:basic_flame_particle ~-1 ~0.5 ~4
particle minecraft:basic_flame_particle ~-1 ~0.5 ~5
particle minecraft:basic_flame_particle ~-1 ~0.5 ~6
particle minecraft:basic_flame_particle ~-1 ~0.5 ~9
particle minecraft:basic_flame_particle ~-1 ~0.5 ~10
particle minecraft:basic_flame_particle ~-1 ~0.5 ~11
particle minecraft:basic_flame_particle ~-1 ~0.5 ~12
particle minecraft:basic_flame_particle ~-1 ~0.5 ~13
particle minecraft:basic_flame_particle ~-1 ~0.5 ~14
particle minecraft:basic_flame_particle ~-1 ~0.5 ~23
particle minecraft:basic_flame_particle ~0 ~0.5 ~-24
particle minecraft:basic_flame_particle ~0 ~0.5 ~-23
particle minecraft:basic_flame_particle ~0 ~0.5 ~-13
particle minecraft:basic_flame_particle ~0 ~0.5 ~-8
particle minecraft:basic_flame_particle ~0 ~0.5 ~-7
particle minecraft:basic_flame_particle ~0 ~0.5 ~-6
particle minecraft:basic_flame_particle ~0 ~0.5 ~-5
particle minecraft:basic_flame_particle ~0 ~0.5 ~0
particle minecraft:basic_flame_particle ~0 ~0.5 ~1
particle minecraft:basic_flame_particle ~0 ~0.5 ~2
particle minecraft:basic_flame_particle ~0 ~0.5 ~3
particle minecraft:basic_flame_particle ~0 ~0.5 ~4
particle minecraft:basic_flame_particle ~0 ~0.5 ~5
particle minecraft:basic_flame_particle ~0 ~0.5 ~6
particle minecraft:basic_flame_particle ~0 ~0.5 ~9
particle minecraft:basic_flame_particle ~0 ~0.5 ~10
particle minecraft:basic_flame_particle ~0 ~0.5 ~11
particle minecraft:basic_flame_particle ~0 ~0.5 ~12
particle minecraft:basic_flame_particle ~0 ~0.5 ~13
particle minecraft:basic_flame_particle ~0 ~0.5 ~14
particle minecraft:basic_flame_particle ~0 ~0.5 ~23
particle minecraft:basic_flame_particle ~0 ~0.5 ~24
particle minecraft:basic_flame_particle ~1 ~0.5 ~-23
particle minecraft:basic_flame_particle ~1 ~0.5 ~-13
particle minecraft:basic_flame_particle ~1 ~0.5 ~-8
particle minecraft:basic_flame_particle ~1 ~0.5 ~-7
particle minecraft:basic_flame_particle ~1 ~0.5 ~-6
particle minecraft:basic_flame_particle ~1 ~0.5 ~0
particle minecraft:basic_flame_particle ~1 ~0.5 ~1
particle minecraft:basic_flame_particle ~1 ~0.5 ~2
particle minecraft:basic_flame_particle ~1 ~0.5 ~3
particle minecraft:basic_flame_particle ~1 ~0.5 ~4
particle minecraft:basic_flame_particle ~1 ~0.5 ~5
particle minecraft:basic_flame_particle ~1 ~0.5 ~6
particle minecraft:basic_flame_particle ~1 ~0.5 ~9
particle minecraft:basic_flame_particle ~1 ~0.5 ~10
particle minecraft:basic_flame_particle ~1 ~0.5 ~11
particle minecraft:basic_flame_particle ~1 ~0.5 ~12
particle minecraft:basic_flame_particle ~1 ~0.5 ~13
particle minecraft:basic_flame_particle ~1 ~0.5 ~14
particle minecraft:basic_flame_particle ~1 ~0.5 ~23
particle minecraft:basic_flame_particle ~2 ~0.5 ~-23
particle minecraft:basic_flame_particle ~2 ~0.5 ~-13
particle minecraft:basic_flame_particle ~2 ~0.5 ~1
particle minecraft:basic_flame_particle ~2 ~0.5 ~2
particle minecraft:basic_flame_particle ~2 ~0.5 ~3
particle minecraft:basic_flame_particle ~2 ~0.5 ~4
particle minecraft:basic_flame_particle ~2 ~0.5 ~5
particle minecraft:basic_flame_particle ~2 ~0.5 ~6
particle minecraft:basic_flame_particle ~2 ~0.5 ~7
particle minecraft:basic_flame_particle ~2 ~0.5 ~8
particle minecraft:basic_flame_particle ~2 ~0.5 ~9
particle minecraft:basic_flame_particle ~2 ~0.5 ~10
particle minecraft:basic_flame_particle ~2 ~0.5 ~11
particle minecraft:basic_flame_particle ~2 ~0.5 ~12
particle minecraft:basic_flame_particle ~2 ~0.5 ~13
particle minecraft:basic_flame_particle ~2 ~0.5 ~14
particle minecraft:basic_flame_particle ~2 ~0.5 ~23
particle minecraft:basic_flame_particle ~3 ~0.5 ~-23
particle minecraft:basic_flame_particle ~3 ~0.5 ~-13
particle minecraft:basic_flame_particle ~3 ~0.5 ~1
particle minecraft:basic_flame_particle ~3 ~0.5 ~2
particle minecraft:basic_flame_particle ~3 ~0.5 ~3
particle minecraft:basic_flame_particle ~3 ~0.5 ~4
particle minecraft:basic_flame_particle ~3 ~0.5 ~5
particle minecraft:basic_flame_particle ~3 ~0.5 ~6
particle minecraft:basic_flame_particle ~3 ~0.5 ~7
particle minecraft:basic_flame_particle ~3 ~0.5 ~8
particle minecraft:basic_flame_particle ~3 ~0.5 ~9
particle minecraft:basic_flame_particle ~3 ~0.5 ~10
particle minecraft:basic_flame_particle ~3 ~0.5 ~11
particle minecraft:basic_flame_particle ~3 ~0.5 ~12
particle minecraft:basic_flame_particle ~3 ~0.5 ~13
particle minecraft:basic_flame_particle ~3 ~0.5 ~14
particle minecraft:basic_flame_particle ~3 ~0.5 ~23
particle minecraft:basic_flame_particle ~4 ~0.5 ~-23
particle minecraft:basic_flame_particle ~4 ~0.5 ~-13
particle minecraft:basic_flame_particle ~4 ~0.5 ~2
particle minecraft:basic_flame_particle ~4 ~0.5 ~3
particle minecraft:basic_flame_particle ~4 ~0.5 ~4
particle minecraft:basic_flame_particle ~4 ~0.5 ~5
particle minecraft:basic_flame_particle ~4 ~0.5 ~6
particle minecraft:basic_flame_particle ~4 ~0.5 ~7
particle minecraft:basic_flame_particle ~4 ~0.5 ~8
particle minecraft:basic_flame_particle ~4 ~0.5 ~9
particle minecraft:basic_flame_particle ~4 ~0.5 ~10
particle minecraft:basic_flame_particle ~4 ~0.5 ~11
particle minecraft:basic_flame_particle ~4 ~0.5 ~12
particle minecraft:basic_flame_particle ~4 ~0.5 ~13
particle minecraft:basic_flame_particle ~4 ~0.5 ~23
particle minecraft:basic_flame_particle ~5 ~0.5 ~-23
particle minecraft:basic_flame_particle ~5 ~0.5 ~-13
particle minecraft:basic_flame_particle ~5 ~0.5 ~-12
particle minecraft:basic_flame_particle ~5 ~0.5 ~3
particle minecraft:basic_flame_particle ~5 ~0.5 ~4
particle minecraft:basic_flame_particle ~5 ~0.5 ~5
particle minecraft:basic_flame_particle ~5 ~0.5 ~6
particle minecraft:basic_flame_particle ~5 ~0.5 ~7
particle minecraft:basic_flame_particle ~5 ~0.5 ~8
particle minecraft:basic_flame_particle ~5 ~0.5 ~9
particle minecraft:basic_flame_particle ~5 ~0.5 ~10
particle minecraft:basic_flame_particle ~5 ~0.5 ~11
particle minecraft:basic_flame_particle ~5 ~0.5 ~12
particle minecraft:basic_flame_particle ~5 ~0.5 ~13
particle minecraft:basic_flame_particle ~5 ~0.5 ~23
particle minecraft:basic_flame_particle ~6 ~0.5 ~-23
particle minecraft:basic_flame_particle ~6 ~0.5 ~-12
particle minecraft:basic_flame_particle ~6 ~0.5 ~4
particle minecraft:basic_flame_particle ~6 ~0.5 ~5
particle minecraft:basic_flame_particle ~6 ~0.5 ~6
particle minecraft:basic_flame_particle ~6 ~0.5 ~7
particle minecraft:basic_flame_particle ~6 ~0.5 ~8
particle minecraft:basic_flame_particle ~6 ~0.5 ~9
particle minecraft:basic_flame_particle ~6 ~0.5 ~10
particle minecraft:basic_flame_particle ~6 ~0.5 ~12
particle minecraft:basic_flame_particle ~6 ~0.5 ~13
particle minecraft:basic_flame_particle ~6 ~0.5 ~23
particle minecraft:basic_flame_particle ~7 ~0.5 ~-22
particle minecraft:basic_flame_particle ~7 ~0.5 ~-12
particle minecraft:basic_flame_particle ~7 ~0.5 ~-11
particle minecraft:basic_flame_particle ~7 ~0.5 ~8
particle minecraft:basic_flame_particle ~7 ~0.5 ~12
particle minecraft:basic_flame_particle ~7 ~0.5 ~22
particle minecraft:basic_flame_particle ~8 ~0.5 ~-22
particle minecraft:basic_flame_particle ~8 ~0.5 ~-11
particle minecraft:basic_flame_particle ~8 ~0.5 ~11
particle minecraft:basic_flame_particle ~8 ~0.5 ~12
particle minecraft:basic_flame_particle ~8 ~0.5 ~22
particle minecraft:basic_flame_particle ~9 ~0.5 ~-22
particle minecraft:basic_flame_particle ~9 ~0.5 ~-10
particle minecraft:basic_flame_particle ~9 ~0.5 ~10
particle minecraft:basic_flame_particle ~9 ~0.5 ~11
particle minecraft:basic_flame_particle ~9 ~0.5 ~22
particle minecraft:basic_flame_particle ~10 ~0.5 ~-21
particle minecraft:basic_flame_particle ~10 ~0.5 ~-10
particle minecraft:basic_flame_particle ~10 ~0.5 ~-9
particle minecraft:basic_flame_particle ~10 ~0.5 ~9
particle minecraft:basic_flame_particle ~10 ~0.5 ~10
particle minecraft:basic_flame_particle ~10 ~0.5 ~21
particle minecraft:basic_flame_particle ~11 ~0.5 ~-21
particle minecraft:basic_flame_particle ~11 ~0.5 ~-9
particle minecraft:basic_flame_particle ~11 ~0.5 ~-8
particle minecraft:basic_flame_particle ~11 ~0.5 ~-7
particle minecraft:basic_flame_particle ~11 ~0.5 ~8
particle minecraft:basic_flame_particle ~11 ~0.5 ~9
particle minecraft:basic_flame_particle ~11 ~0.5 ~21
particle minecraft:basic_flame_particle ~12 ~0.5 ~-20
particle minecraft:basic_flame_particle ~12 ~0.5 ~-7
particle minecraft:basic_flame_particle ~12 ~0.5 ~-6
particle minecraft:basic_flame_particle ~12 ~0.5 ~6
particle minecraft:basic_flame_particle ~12 ~0.5 ~7
particle minecraft:basic_flame_particle ~12 ~0.5 ~8
particle minecraft:basic_flame_particle ~12 ~0.5 ~20
particle minecraft:basic_flame_particle ~13 ~0.5 ~-6
particle minecraft:basic_flame_particle ~13 ~0.5 ~-5
particle minecraft:basic_flame_particle ~13 ~0.5 ~-4
particle minecraft:basic_flame_particle ~13 ~0.5 ~-3
particle minecraft:basic_flame_particle ~13 ~0.5 ~3
particle minecraft:basic_flame_particle ~13 ~0.5 ~4
particle minecraft:basic_flame_particle ~13 ~0.5 ~5
particle minecraft:basic_flame_particle ~13 ~0.5 ~6
particle minecraft:basic_flame_particle ~14 ~0.5 ~-19
particle minecraft:basic_flame_particle ~14 ~0.5 ~-3
particle minecraft:basic_flame_particle ~14 ~0.5 ~-2
particle minecraft:basic_flame_particle ~14 ~0.5 ~-1
particle minecraft:basic_flame_particle ~14 ~0.5 ~0
particle minecraft:basic_flame_particle ~14 ~0.5 ~1
particle minecraft:basic_flame_particle ~14 ~0.5 ~2
particle minecraft:basic_flame_particle ~14 ~0.5 ~3
particle minecraft:basic_flame_particle ~14 ~0.5 ~4
particle minecraft:basic_flame_particle ~14 ~0.5 ~19
particle minecraft:basic_flame_particle ~15 ~0.5 ~-18
particle minecraft:basic_flame_particle ~15 ~0.5 ~18
particle minecraft:basic_flame_particle ~16 ~0.5 ~-17
particle minecraft:basic_flame_particle ~16 ~0.5 ~17
particle minecraft:basic_flame_particle ~17 ~0.5 ~-16
particle minecraft:basic_flame_particle ~17 ~0.5 ~16
particle minecraft:basic_flame_particle ~18 ~0.5 ~-15
particle minecraft:basic_flame_particle ~18 ~0.5 ~15
particle minecraft:basic_flame_particle ~19 ~0.5 ~-14
particle minecraft:basic_flame_particle ~19 ~0.5 ~14
particle minecraft:basic_flame_particle ~20 ~0.5 ~-12
particle minecraft:basic_flame_particle ~20 ~0.5 ~12
particle minecraft:basic_flame_particle ~21 ~0.5 ~-11
particle minecraft:basic_flame_particle ~21 ~0.5 ~-10
particle minecraft:basic_flame_particle ~21 ~0.5 ~10
particle minecraft:basic_flame_particle ~21 ~0.5 ~11
particle minecraft:basic_flame_particle ~22 ~0.5 ~-9
particle minecraft:basic_flame_particle ~22 ~0.5 ~-8
particle minecraft:basic_flame_particle ~22 ~0.5 ~-7
particle minecraft:basic_flame_particle ~22 ~0.5 ~7
particle minecraft:basic_flame_particle ~22 ~0.5 ~8
particle minecraft:basic_flame_particle ~22 ~0.5 ~9
particle minecraft:basic_flame_particle ~23 ~0.5 ~-6
particle minecraft:basic_flame_particle ~23 ~0.5 ~-5
particle minecraft:basic_flame_particle ~23 ~0.5 ~-4
particle minecraft:basic_flame_particle ~23 ~0.5 ~-3
particle minecraft:basic_flame_particle ~23 ~0.5 ~-2
particle minecraft:basic_flame_particle ~23 ~0.5 ~-1
particle minecraft:basic_flame_particle ~23 ~0.5 ~0
particle minecraft:basic_flame_particle ~23 ~0.5 ~1
particle minecraft:basic_flame_particle ~23 ~0.5 ~2
particle minecraft:basic_flame_particle ~23 ~0.5 ~3
particle minecraft:basic_flame_particle ~23 ~0.5 ~4
particle minecraft:basic_flame_particle ~23 ~0.5 ~5
particle minecraft:basic_flame_particle ~23 ~0.5 ~6
particle minecraft:basic_flame_particle ~24 ~0.5 ~0
