setblock ~-2 ~ ~-2 allium replace
setblock ~-2 ~ ~-1 pink_petals replace
setblock ~-2 ~ ~0 rose_bush replace
setblock ~-2 ~ ~1 pitcher_plant replace
setblock ~-2 ~ ~2 blue_orchid replace
setblock ~-1 ~ ~-2 lily_of_the_valley replace
setblock ~-1 ~ ~-1 bush replace
setblock ~-1 ~ ~0 tall_grass replace
setblock ~-1 ~ ~1 white_tulip replace
setblock ~-1 ~ ~2 pitcher_plant replace
setblock ~0 ~ ~-2 dandelion replace
setblock ~0 ~ ~-1 blue_orchid replace
setblock ~0 ~ ~0 blue_orchid replace
setblock ~0 ~ ~1 allium replace
setblock ~0 ~ ~2 dandelion replace
setblock ~1 ~ ~-2 rose_bush replace
setblock ~1 ~ ~-1 red_tulip replace
setblock ~1 ~ ~0 pink_petals replace
setblock ~1 ~ ~1 poppy replace
setblock ~1 ~ ~2 bush replace
setblock ~2 ~ ~-2 pink_petals replace
setblock ~2 ~ ~-1 sunflower replace
setblock ~2 ~ ~0 peony replace
setblock ~2 ~ ~1 pink_tulip replace
setblock ~2 ~ ~2 dandelion replace
